name: Release - Verify
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - alpha/*/*
      - release/*/*
      - main

jobs:
  try:
    uses: kungfu-trader/workflows/.github/workflows/.release-verify.yml@v1
    with:
      build-runner-linux: app-builder-linux
      node-version: "16"
      builder-container: docker.io/kungfutrader/docs-builder:v1.0.0-alpha.10
      enable-linux: true
      enable-macos: false
      enable-windows: false
      publish-aws-ci: false
      publish-versioning: false
      bucket-staging-user: kungfu-docs-staging
      preview-files: '^index.html$'
      max-preview-links: '1'
    secrets:
      AWS_USER_ACCESS_KEY_ID: ${{ secrets.AWS_CN_ACCESS_KEY_ID }}
      AWS_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_CN_SECRET_ACCESS_KEY }}
      NODE_AUTH_TOKEN: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
  
  verify:
    needs: try
    runs-on: ubuntu-22.04
    steps:
      - name: report
        run: echo verified
